# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.srcs/sources_1/ip/squareRoot_26bits/squareRoot_26bits.xci
# IP: The module: 'squareRoot_26bits' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.srcs/sources_1/ip/squareRoot_26bits/squareRoot_26bits_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'squareRoot_26bits'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.srcs/sources_1/ip/squareRoot_26bits/squareRoot_26bits.xci
# IP: The module: 'squareRoot_26bits' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.srcs/sources_1/ip/squareRoot_26bits/squareRoot_26bits_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'squareRoot_26bits'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
