# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.cache/wt [current_project]
set_property parent.project_path C:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo c:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet c:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.srcs/sources_1/ip/squareRoot_26bits/squareRoot_26bits.xci
set_property is_locked true [get_files c:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.srcs/sources_1/ip/squareRoot_26bits/squareRoot_26bits.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir C:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.runs/squareRoot_26bits_synth_1 -new_name squareRoot_26bits -ip [get_ips squareRoot_26bits]]

if { $cached_ip eq {} } {

synth_design -top squareRoot_26bits -part xc7z020clg484-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix squareRoot_26bits_ squareRoot_26bits.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ squareRoot_26bits_stub.v
 lappend ipCachedFiles squareRoot_26bits_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ squareRoot_26bits_stub.vhdl
 lappend ipCachedFiles squareRoot_26bits_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ squareRoot_26bits_sim_netlist.v
 lappend ipCachedFiles squareRoot_26bits_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ squareRoot_26bits_sim_netlist.vhdl
 lappend ipCachedFiles squareRoot_26bits_sim_netlist.vhdl

 config_ip_cache -add -dcp squareRoot_26bits.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips squareRoot_26bits]
}

rename_ref -prefix_all squareRoot_26bits_

write_checkpoint -force -noxdef squareRoot_26bits.dcp

catch { report_utilization -file squareRoot_26bits_utilization_synth.rpt -pb squareRoot_26bits_utilization_synth.pb }

if { [catch {
  file copy -force C:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.runs/squareRoot_26bits_synth_1/squareRoot_26bits.dcp c:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.srcs/sources_1/ip/squareRoot_26bits/squareRoot_26bits.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub c:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.srcs/sources_1/ip/squareRoot_26bits/squareRoot_26bits_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub c:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.srcs/sources_1/ip/squareRoot_26bits/squareRoot_26bits_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim c:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.srcs/sources_1/ip/squareRoot_26bits/squareRoot_26bits_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim c:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.srcs/sources_1/ip/squareRoot_26bits/squareRoot_26bits_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force C:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.runs/squareRoot_26bits_synth_1/squareRoot_26bits.dcp c:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.srcs/sources_1/ip/squareRoot_26bits/squareRoot_26bits.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force C:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.runs/squareRoot_26bits_synth_1/squareRoot_26bits_stub.v c:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.srcs/sources_1/ip/squareRoot_26bits/squareRoot_26bits_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.runs/squareRoot_26bits_synth_1/squareRoot_26bits_stub.vhdl c:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.srcs/sources_1/ip/squareRoot_26bits/squareRoot_26bits_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.runs/squareRoot_26bits_synth_1/squareRoot_26bits_sim_netlist.v c:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.srcs/sources_1/ip/squareRoot_26bits/squareRoot_26bits_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.runs/squareRoot_26bits_synth_1/squareRoot_26bits_sim_netlist.vhdl c:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.srcs/sources_1/ip/squareRoot_26bits/squareRoot_26bits_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir C:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.ip_user_files/ip/squareRoot_26bits]} {
  catch { 
    file copy -force c:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.srcs/sources_1/ip/squareRoot_26bits/squareRoot_26bits_stub.v C:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.ip_user_files/ip/squareRoot_26bits
  }
}

if {[file isdir C:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.ip_user_files/ip/squareRoot_26bits]} {
  catch { 
    file copy -force c:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.srcs/sources_1/ip/squareRoot_26bits/squareRoot_26bits_stub.vhdl C:/Users/Mike/Documents/ECE_492_SeniorProject/ultrasonicRadar2D/ultrasonicRadar2D.ip_user_files/ip/squareRoot_26bits
  }
}
